import { getReports } from '../../api/aiService';
import { useFetch } from '../../hooks/useFetch';
import { BrainCircuit, Loader2, Calendar, AlertCircle } from 'lucide-react';
import { formatDate } from '../../utils/formatters';

export default function AIInsightsPage() {
  const { data, loading, error } = useFetch(getReports);
  const reports = data?.reports || [];

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      <div className="flex items-center gap-4 mb-8">
        <div className="p-3 bg-purple-100 text-purple-600 rounded-2xl">
          <BrainCircuit size={28} />
        </div>
        <div>
          <h1 className="text-3xl font-bold text-gray-900">AI Insights Archive</h1>
          <p className="text-gray-500 font-medium">Historical analysis reports generated by Gemini AI.</p>
        </div>
      </div>

      {loading && (
        <div className="flex flex-col items-center justify-center py-20 text-gray-400">
          <Loader2 className="animate-spin mb-4" size={32} />
          <p>Loading reports...</p>
        </div>
      )}

      {error && (
        <div className="p-4 bg-red-50 text-red-600 rounded-xl flex items-center gap-3 font-medium">
          <AlertCircle />
          Failed to load reports.
        </div>
      )}

      {!loading && !error && reports.length === 0 && (
        <div className="text-center py-20 bg-white rounded-3xl border border-gray-100 shadow-sm">
          <BrainCircuit className="mx-auto text-gray-300 mb-4" size={48} />
          <h3 className="text-xl font-bold text-gray-900 mb-2">No Insights Yet</h3>
          <p className="text-gray-500 max-w-md mx-auto">
            Generate your first batch analysis from the dashboard to see actionable AI insights here.
          </p>
        </div>
      )}

      <div className="space-y-6">
        {reports.map((report) => (
          <div key={report._id} className="bg-white rounded-3xl overflow-hidden border border-gray-100 shadow-sm">
            <div className="bg-gradient-to-r from-gray-50 to-white px-6 py-4 border-b border-gray-100 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <span className="px-3 py-1 bg-indigo-100 text-indigo-700 text-xs font-bold uppercase tracking-wider rounded-lg">
                  {report.type} Report
                </span>
                <span className="flex items-center text-sm font-medium text-gray-500 gap-1.5">
                  <Calendar size={14} />
                  {formatDate(report.createdAt)}
                </span>
              </div>
            </div>
            <div className="p-6">
              <div className="prose prose-indigo max-w-none">
                <pre className="whitespace-pre-wrap font-sans text-gray-700 leading-relaxed text-sm bg-gray-50/50 p-6 rounded-2xl border border-gray-100">
                  {report.reportContent || report.rawResponse}
                </pre>
              </div>
            </div>
            <div className="px-6 py-4 bg-gray-50 border-t border-gray-100 text-xs text-gray-400 font-mono flex gap-4">
              <span>ID: {report._id}</span>
              <span>Snapshot Size: {JSON.stringify(report.dataSnapshot || {}).length} bytes</span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
